#!/usr/bin/env bash
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Variables
declare -A gaps
declare -A color

gaps["top"]="24"
gaps["bottom"]="24"
gaps["left"]="24"
gaps["right"]="24"
gaps["inner"]="24"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# Tiling setting
yabai -m config layout bsp

yabai -m config top_padding "${gaps["top"]}"
yabai -m config bottom_padding "${gaps["bottom"]}"
yabai -m config left_padding "${gaps["left"]}"
yabai -m config right_padding "${gaps["right"]}"
yabai -m config window_gap "${gaps["inner"]}"

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m config window_topmost off
yabai -m config window_opacity on
yabai -m config window_shadow float

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config split_ratio 0.50

yabai -m config auto_balance off

yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# Spaces
yabai -m space 1 --label social  #  聆
yabai -m space 2 --label browser # 
yabai -m space 3 --label coding  # 
yabai -m space 4 --label design  # 
yabai -m space 5 --label misc    #   ﴯ

# Window
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config window_shadow on
yabai -m config window_border off
yabai -m config window_border_placement inset
yabai -m config window_border_width 6
yabai -m config window_border_radius -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color 0xFF000000
yabai -m config normal_window_border_color 0xFF303246
yabai -m config insert_window_border_color 0xffd75f5f
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.70

# Apps
yabai -m rule --add app="^1Password$" sticky=on manage=off
yabai -m rule --add app="^CleanMyMac X$" sticky=on manage=off
yabai -m rule --add app="^Microsoft Teams classic$" manage=off
yabai -m rule --add app="^Mimestream$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Spotify$" sticky=on manage=off
yabai -m rule --add app="^Stats$" sticky=on manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^WhatsApp" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^Setapp$" manage=off
yabai -m rule --add app="^HP Easy Scan$" manage=off
yabai -m rule --add app="^Tower$" manage=off
yabai -m rule --add app="^Kaleidoscope$" manage=off
yabai -m rule --add app="^RapidAPI$" manage=off
yabai -m rule --add app="^Window$" manage=off

# Browser
yabai -m rule --add app="^Arc$" manage=on
yabai -m rule --add label="Arc PiP" app="^Arc$" title="^$" manage=off
yabai -m rule --add label="Little Arc Launcher" app="^Arc$" title="^Space 1$" manage=off
yabai -m rule --add app="^Safari$" manage=on
yabai -m rule --add app="^Google Chrome$" manage=on border=on
yabai -m rule --add app="^Firefox$" manage=on border=on

# System
yabai -m rule --add app="System Information" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Books$" manage=off
yabai -m rule --add app="^TV$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Finder$" manage=off sticky=on
yabai -m rule --add app="^Installer$" sticky=on manage=off
yabai -m rule --add app="Photo Booth" manage=off
yabai -m rule --add app="Software Update" manage=off
yabai -m rule --add app="Reminders" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Preview" manage=off

# Statusbar spacing
yabai -m config external_bar all:26:0

echo "yabai configuration loaded.."
