#!/usr/bin/env bash
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Variables
declare -A gaps
declare -A color

gaps["top"]="10"
gaps["bottom"]="10"
gaps["left"]="10"
gaps["right"]="10"
gaps["inner"]="10"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# Tiling setting
yabai -m config layout bsp

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config window_topmost              off
yabai -m config window_opacity              on
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              ctrl
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# Spaces
yabai -m space 1 --label social
yabai -m space 2 --label browser
yabai -m space 3 --label coding
yabai -m space 4 --label design
yabai -m space 5 --label misc

# Apps
yabai -m rule --add label="1Password" app="^1Password$" sticky=on manage=off
yabai -m rule --add label="CleanMyMac X" app="^CleanMyMac X$" sticky=on manage=off
yabai -m rule --add label="Microsoft Teams" app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Mimestream$" manage=off
yabai -m rule --add label="Slack" app="^Slack$" manage=off
yabai -m rule --add label="Slack" app="^Discord$" manage=off
yabai -m rule --add label="Spotify" app="^Spotify$" sticky=on manage=off
yabai -m rule --add label="Stats" app="^Stats$" sticky=on manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^WhatsApp" manage=off
yabai -m rule --add label="Fig" app="^fig$" manage=off border=off
yabai -m rule --add app="^Dash" manage=off

# Browser
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off opacity=1.0
yabai -m rule --add label="Firefox" app="^Firefox$" opacity=1.0

# System
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Calendar" app="^Calendar$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off sticky=on
yabai -m rule --add label="Installer" app="^Installer$" sticky=on manage=off
yabai -m rule --add label="Photo Booth" title="^Photo Booth$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off

echo "yabai configuration loaded.."