[theme.custom]
panel_bg    = "#161616"
surface0    = "#262626"
surface1    = "#393939"
surface_dim = "#262626"
text        = "#f2f4f8"
subtext0    = "#dde1e6"
overlay0    = "#525252"
overlay1    = "#6f6f6f"
accent      = "#33b1ff"
blue        = "#33b1ff"
green       = "#42be65"
yellow      = "#ffe97b"
red         = "#ee5396"
peach       = "#ff832b"
teal        = "#3ddbd9"
mauve       = "#be95ff"
