[theme.custom]
panel_bg    = "#ffffff"
surface0    = "#f4f4f4"
surface1    = "#e0e0e0"
surface_dim = "#f4f4f4"
text        = "#161616"
subtext0    = "#393939"
overlay0    = "#8d8d8d"
overlay1    = "#6f6f6f"
accent      = "#0f62fe"
blue        = "#0f62fe"
green       = "#24a148"
yellow      = "#b28600"
red         = "#da1e28"
peach       = "#e8590c"
teal        = "#007d79"
mauve       = "#8a3ffc"
