export ZSH="$HOME/.local/share/sheldon/repos/github.com/ohmyzsh/ohmyzsh"

plugins=(
  git
  npm
  yarn
  nvm
  sudo
  ssh-agent
  gpg-agent
  macos
  common-aliases
  command-not-found
)

# sheldon
eval "$(sheldon source)"

# disable analytics
export HOMEBREW_NO_ANALYTICS=1

# local path
PATH=/bin:/usr/bin:/usr/local/bin:${PATH}
export PATH

# open jdk
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi
PATH=$(pyenv root)/shims:$PATH

# android sdk
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools

# path
export PATH="$HOME/.local/bin:$PATH"

# fnm node version manager
eval "$(fnm env --use-on-cd)"

# zoxide
eval "$(zoxide init zsh)"

# auto title
DISABLE_AUTO_TITLE="true"

# local configuration
if [[ -f "$HOME/.zshlocal" ]]; then
  source "$HOME/.zshlocal"
fi

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
