\command -v sheldon &>/dev/null ||
  (curl --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh |
    bash -s -- --repo rossmacarthur/sheldon --to ~/.local/bin)

autoload -Uz compinit
compinit -i

# editor
export EDITOR=hx

# sheldon
eval "$(sheldon source)"

# disable analytics
export HOMEBREW_NO_ANALYTICS=1

# azure function telemetry opt out
export FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT=1

# homebrew
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

# home local path
export PATH="$HOME/.local/bin:$PATH"

# local path
export PATH=/bin:/usr/bin:/usr/local/bin:${PATH}

# open jdk
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# cargo
export PATH=$HOME/.cargo/bin:$PATH

# llvm
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"

# node
export PATH="$PATH:$(npm get prefix)/bin"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi
PATH=$(pyenv root)/shims:$PATH

# android sdk
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools

# zoxide
eval "$(zoxide init zsh)"

# auto title
DISABLE_AUTO_TITLE="true"

# EXPO disable keychain
EXPO_NO_KEYCHAIN=1

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# rbenv
eval "$(rbenv init - zsh)"

# zellij
eval "$(zellij setup --generate-auto-start zsh)"

# alias
if [[ -f "$HOME/.alias" ]]; then
  source "$HOME/.alias"
fi

# local
if [[ -f "$HOME/.zshlocal" ]]; then
  source "$HOME/.zshlocal"
fi

# pnpm
export PNPM_HOME="/Users/ksch/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true
