#!/usr/bin/env bash
source "$HOME/.config/sketchybar/colors.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
FONT="Liga SFMono Nerd Font"

bar=(
  color=$BLACK
  shadow=off
  position=top
  sticky=on
  height=27
  blur_radius=50
  padding_right=10
  padding_left=10
  y_offset=0
)

sketchybar --bar "${bar[@]}"

defaults=(
  updates=when_shown
  drawing=on
  cache_scripts=on
  icon.font="$FONT:Bold:17.0"
  icon.color=$BLACK
  icon.padding_left=5
  icon.padding_right=5
  label.font="$FONT:Bold:11"
  label.color=$BLACK
  label.padding_left=3
  label.padding_right=5
  padding_right=3
  padding_left=3
  background.padding_right=10
  background.height=20
  background.corner_radius=2
)

sketchybar --default "${defaults[@]}"

sketchybar -m --add event window_focus \
  --add event window_created \
  --add event window_destroyed \
  --add event layout_change \
  --add event property_change

source "$HOME/.config/sketchybar/items.sh"

sketchybar -m --update

echo "sketchybar configuration loaded..."
